### ISSUE TITLE
All permission at MetaMask

### ISSUE THREAD

**Issue by VishalWaman** [MetaMask/json-rpc-capabilities-middleware#124]
Hi, I am looking to play around to enhance permission of metamask to enable all permission to send on "My behalf" 
below link has few steps which needs "Extracted metamask archive" can you please share this folder to complete below steps.

https://github.com/MetaMask/metamask-extension/blob/develop/docs/add-to-chrome.md
https://eips.ethereum.org/EIPS/eip-2255

@rekmarks @danfinlay

**Comment by VishalWaman** [comment]
@danfinlay @rekmarks can you please guide.

**Comment by brad-decker** [comment]
@VishalWaman -- If you clone the metamask-extension repo locally and follow the steps in the readme to build the application from source, it'll produce the dist/ folder mentioned in the instructions that you linked to.

**Comment by VishalWaman** [comment]
Thanks @brad-decker we are looking for feature where we don’t want “approve” from user, it should be permission which is already given to Dapp

can you guide me to achieve this ?

Basically i want to use metamask without extensions just to make experience of my dapp easy

**Comment by rekmarks** [comment]
@VishalWaman, because we are going to archive this repo (new permission system implemented [here](https://github.com/MetaMask/snaps-skunkworks/tree/54803e63e15732ffb561143c4197ba1de7cd019f/packages/controllers/src/permissions)) I am going to close this issue due to inactivity.

Before I do so, it seems that you are asking whether there is a permission that allows a dapp to send assets on behalf of the user. We have discussed adding such a permissions, and while we may do so at some undetermined point in the future, decided to delegate such functionality to to on-chain code for now.

As for your question re: pre-approving permissions for a particular dapp, we do not support or wish to support that functionality, although you could create a custom build of MetaMask to accomplish it by adding the corresponding state to `initState` in [this file](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/metamask-controller.js). See the new permission controller tests for what that state should look like.

If you have any further questions along these lines, I recommend creating an issue and tagging me on the main extension repository.
