### ISSUE TITLE
Caveats subsystem spec

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/json-rpc-capabilities-middleware#19]
**Overview**
This is a draft spec for the caveat subsystem.

First, recall the permissions object:
```js
{
  method: 'restrictedMethodName',
  id: '63b225d0-414e-4a2d-8067-c34499c984c7', // UUID string
  date: 0, // unix time of creation
  granter: 'another.domain.com', // Another domain string if this permission was created by delegation.
  caveats: [ // An optional array of objects describing limitations on the method reference.
    {
      type: 'static', // The static caveat only returns the specified static response value.
      value: 'Always this!'
    }
  ]
}
```

Now, broadly and conceptually, we have two different kinds of caveats,
1. **Modifiers**, i.e. caveats that alter the RPC request in some way.
2. **Conditions**, i.e. caveats that check for some condition relative to themselves and the RPC request, and halt the request if the check fails.

For each request, the middleware checks if the required permissions have been granted to the requesting domain, and then iterates over the `caveats` array. Modifiers caveats are applied as they are encountered, and condition caveats have a `validate(request)` method that is called, returning whether the request is valid or not with respect to the condition they encode.

The middleware has no knowledge of what the condition is; it only checks whether the `validate(request)` method returns `true` or `false`. This allows the client application (i.e. MetaMask) to create arbitrarily complex conditions while keeping the `rpc-cap` API surface small and its logic simple.

**API**
- `addCaveat(permission, options)`
- `updateCaveat(permission, options, type, [,subType])`
- `deleteCaveat(permission, type, [,subType])`

**Caveat Types**
- `static` (modifier)
  - Characteristics
    - Short-circuit the remote procedure call and return a static value.
      - All other caveats are still applied/enforced.
    - Incompatible with `fixed-params` caveats (no remote procedure call is made; no parameters are needed)
  - Form:
    ```js
    {
        type: 'static',
        value: 'Always this!'
    }
    ```
- `fixed-params` (modifier)
  - Characteristics
    - Specifies fixed parameters for all or some of the parameters for a remote procedure call.
    - If there is only one parameter, it must be fixed, otherwise this caveat is meaningless.
    - Incompatible with `static` caveats (see above)
  - Form:
    ```js
    {
        type: 'fixed-params',
        value: [{fixed: true, value: 'foo'}, {fixed: false}, {fixed: true, value: 'bar'}]
    }
    ```
- `condition` (condition)
  - Characteristics
    - This type is intended to cover **all** conditional caveats.
    - Specifies an arbitrary `value` and validator function that takes an RPC request and checks that the request is valid with respect to the `value` and the request.
      - `value` can be `null` but not `undefined`
      - The validator function is specified by the client application and the middleware has no knowledge of its internals; it merely calls a `validate` function that wraps the actual validator function
    - Has a `subType` defined by the client application, and a permission can only have one `condition` caveat of each `subType`
    - Compatible with all other caveat types and other `condition` caveats (subject to `subType` limitation)
  - Form: (`requiredAccount` example)
    ```js
    {
       type: 'condition',
       subType: 'requiredAccount', // defined by client
       description: 'Checks if the request was made using a valid account.', // show this in the UI
       value: ['0xabc123...', ...], // value defined outside of validator function for easy modification
       _validator: (req, value) => value.includes(req.options.account), // this is the function defined by the client; it is not directly called by the middleware
       validate: // this is the function called by the middleware for each request and caveat 
         function (req) {
           return this._validator(req, this.value)
         },
    }
    ```

**Notes**
Feedback encouraged. I may be missing stuff I have yet to encounter as I implement this. Examples of how #7 would look in practice in this model appreciated.

Several possible improvements are already apparent. For instance, the subsystem API could be extended to include a function like `validate(request, caveat)` and remove the `validate` property from `condition` caveats.

@danfinlay

**Comment by danfinlay** [comment]
## Static Caveats

> we have two different kinds of caveats,

(modifiers and conditions): Do we have other examples of modifiers? I almost think, for example, the `static` type, which was really a very MVP thing, could have also been a `results-filter` type or something, and be considered a condition and not a modifier. Just trying to unite the types for the sake of reducing the abstraction's complexity. There's also no good way to `AND` a static caveat with others, which helps indicate that it's maybe not a great abstraction anyways.

## Caveats as middleware

Considering this whole library is built as [rpc-engine](https://github.com/MetaMask/json-rpc-engine) middleware, which is made for resolving, revising, or not interrupting a request, they almost seem like a perfect format for caveats...

Advantage: While this current proposal passes `validate()` a `req`, a future caveat might want to mutate the request before passing it on, or maybe mutate or append to the response, or wait for the main response before filtering it, etc. All of this is already handled by the current json-rpc-middleware pattern.

## Add caveats to constructor

For simplicity, I think we should be able to construct `RpcCap` with a map/array/set of its supported caveats, which could be something like:

```
const permsController = new RpcCap({
  caveats: {
    filter: filterCaveatMiddlewareConstructor,
    paramLimit: paramLimitCaveatMiddlewareConstructor,
  }
})
```

I think this could make a pretty simple internal implementation, too, you'd:

- Check the incoming request & its domain, pull up any permission object.
- Pass the request through its caveat middlewares on a loop.

This would encourage a distinction between a `caveatMiddlewareConstructor` and a `caveat`: The constructor is passed to the `RpcCap` class, and the `caveat` is produced by passing the serialized caveat data to the `caveatMiddlewareConstructor`, producing a live `caveat` middleware function, ready to enforce a single domain's rules. (We would want to initialize these on a per-request basis, to avoid the number of functions constructed but not used).

Example, maybe something like:
```javascript
async handleRequest(domain, req, res, next) {

  const permission = this.getPermission(req, domain)

  const caveats = permission.caveats.map((serializedCaveat) => {
    const constructor = this.getCaveatConstructorFor(serializedCaveat)
    const caveat = new constructor({
      serializedCaveat
    })
  })

  return await this.iterateMiddleware(caveats, req, res, next)
}
```

Except that it also needs to traverse the _chain of delegation_ as well as the array of caveats. I should probably enhance that diagram, like:

<img width="553" alt="Screen Shot 2019-05-31 at 2 00 50 PM" src="https://user-images.githubusercontent.com/542863/58734606-b07b6080-83ac-11e9-971d-fbd9aedca45f.png">

Constructing/persisting these on a per-request basis is also an important security feature for stateful caveats: If we wanted to enforce a spending limit, we have to guarantee that the caveat's internal counter is persisted _before_ we issue the function call, and the function call itself also needs to be persisted, so that an interruption to the computer does not put the caveat and tx queue out of sync. (For detailed explanation, jump to `2.5    NodeKen: Distributed Orthogonal Persistence` in Mark Miller's [Distributed Electronic Rights in JavaScript](https://storage.googleapis.com/pub-tools-public-publication-data/pdf/40673.pdf).

For this reason, the `middlewareConstructor` objects probably need to be constructed with not only the target serialized `caveat`, but also an ability to emit state updates, maybe following the `gaba` or `obs-store` pattern.

## Fixed-params caveat

I just wanted to note this caveat would probably benefit from allowing a recursive definition. To demonstrate why, imagine a function that accepts an `options` object as its parameter (as all JSON-RPC requests do!). We therefore need a way to define fixed keys on an object, and also fixed positions in arrays within that object (the arguments of a json-rpc request is an array), as well as objects within an array within an object (an options object passed as a json-rpc argument, as used in `signTypedData`), and so forth recursively.

## Other notes

#7 is a totally unrelated approach to this, I'm going to close it, because it's a cheaper and crappier approach to this whole thing imo.

**Comment by danfinlay** [comment]
Hadn’t considered it before, but a middleware/caveat stack could also be composed out of Proxy objects, which are supposedly more performant than function wrapping? https://www.reddit.com/r/javascript/comments/bv8ny6/just_discovered_the_es6_proxy_object_if_you/epnbhvf/?utm_source=share&utm_medium=ios_app

**Comment by danfinlay** [comment]
Actually ignore that, Proxy has slow iOS support, should probably not use yet.

**Comment by danfinlay** [comment]
Master now uses middleware for caveats and has two sample caveats.
